name: CI
on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Test
        run: mvn $MAVEN_CLI_OPTS test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build library
        run: mvn $MAVEN_CLI_OPTS clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build CLI
        run: mvn $MAVEN_CLI_OPTS clean package -Pcli -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy resources
        run: |
          mkdir -p docker/target
          cp target/*.jar docker/target/commons-ip-cits-siard.jar
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: docker
          push: false
          tags: keeps/commons-ip-cits-siard:latest
